### ISSUE TITLE
stderror-eventhandlers

### ISSUE THREAD

**Issue by CCGLLC-knc** [codeinfused/Indy-Hud#1]
Running V1.2 first time and seeing:

![image](https://user-images.githubusercontent.com/41486548/197421481-a3a7ba2f-563a-4ecd-8350-dab23482ad10.png)

**Comment by CCGLLC-knc** [comment]
Hmmm, can't seem to edit above.  Wanted to add what I am seeing on the hud:

![image](https://user-images.githubusercontent.com/41486548/197421565-828f345f-a0f8-4e0e-9dc1-d754b36c469c.png)

**Comment by codeinfused** [comment]
> Running V1.2 first time and seeing:
> 
> ![image](https://user-images.githubusercontent.com/41486548/197421481-a3a7ba2f-563a-4ecd-8350-dab23482ad10.png)

@CCGLLC-knc  Try updating 1.3, I saw this elsewhere and 1.3 changes had fixed it. Hopefully works for yours as well.

**Comment by CCGLLC-knc** [comment]
No errors now - Thanks!
