### ISSUE TITLE
Unclear what the times represent

### ISSUE THREAD

**Issue by CCGLLC-knc** [codeinfused/Indy-Hud#2]
I have a small box with a time in it (10m, 15m, etc.) that I'm unclear about.  What is this suppose to represent?

![image](https://user-images.githubusercontent.com/41486548/199531162-21d06050-2ded-4cae-9a74-987d7dd8d1d8.png)

**Comment by codeinfused** [comment]
@CCGLLC-knc Those are meters distance to the machine :)
