### ISSUE TITLE
STDERROR-EVENTHANDLER

### ISSUE THREAD

**Issue by CCGLLC-knc** [codeinfused/Indy-Hud#3]
Think I got this when I ran away from the industry.

Noticed the HUD stays up even when I am well away from the factory.  Maybe auto-hide it when there are no matches in range?

Anyhow, here is the error:

![image](https://user-images.githubusercontent.com/41486548/199532436-ebf62f7c-954c-4705-a904-49552c3d74d4.png)

and the hud panel:

![image](https://user-images.githubusercontent.com/41486548/199532596-23ccffb5-33d2-4a00-bc32-10ac97d1d3ad.png)

**Comment by CCGLLC-knc** [comment]
Ah, the HUD panel did disappear once I got about a km from the factory.

**Comment by codeinfused** [comment]
Also you can CTRL+Backspace to exit the HUD (or any running script).

**Comment by CCGLLC-knc** [comment]
Probably still want to address the STDERROR portion of this report...
